CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

CREATE TABLE IF NOT EXISTS account(
  id SERIAL PRIMARY KEY,
  email VARCHAR(128) UNIQUE NOT NULL,
  public_id UUID UNIQUE NOT NULL DEFAULT UUID_GENERATE_V4(),
  extra JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_auth_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_unauth_at TIMESTAMP DEFAULT NULL);


CREATE OR REPLACE FUNCTION force_get_account(e VARCHAR(128)) RETURNS RECORD AS '
DECLARE res RECORD;
BEGIN
  SELECT * FROM account WHERE email = e INTO res;
  IF (res IS NULL) THEN
    INSERT INTO account(email) VALUES(e) RETURNING * INTO res;
  END IF;
  RETURN res;
END;'
LANGUAGE PLPGSQL;
